### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mahipat99** [KlaysDe/esp32-s3_usb-keyboard-to-mqtt#1]
I am trying to compile your code, but it gives an elapsedMillis library error all the time.
I can see the library is installed(/esp32-s3_usb-keyboard-to-mqtt/.pio/libdeps/esp32-s3-devkitc-1/elapsedMillis) but still it throws error

```
Processing esp32-s3-devkitc-1 (platform: espressif32; board: esp32-s3-devkitc-1; framework: espidf)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PLATFORM: Espressif 32 (6.5.0) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.50102.0 (5.1.2) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
Reading CMake configuration...
Warning! Flash memory size mismatch detected. Expected 8MB, found 2MB!
Please select a proper value in your `sdkconfig.defaults` or via the `menuconfig` target!
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio/build/esp32-s3-devkitc-1/src/main.o
src/main.cpp:1:10: fatal error: elapsedMillis.h: No such file or directory

***********************************************************************
* Looking for elapsedMillis.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:elapsedMillis.h"
* Web  > https://registry.platformio.org/search?q=header:elapsedMillis.h
*
***********************************************************************

    1 | #include <elapsedMillis.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
Archiving .pio/build/esp32-s3-devkitc-1/esp-idf/app_trace/libapp_trace.a
Indexing .pio/build/esp32-s3-devkitc-1/esp-idf/app_trace/libapp_trace.a
Archiving .pio/build/esp32-s3-devkitc-1/esp-idf/app_update/libapp_update.a
Indexing .pio/build/esp32-s3-devkitc-1/esp-idf/app_update/libapp_update.a
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/src/secure_boot.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/bootloader_flash/src/bootloader_flash.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/bootloader_flash/src/flash_qio_mode.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/bootloader_flash/src/bootloader_flash_config_esp32s3.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/src/bootloader_utility.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/src/flash_partitions.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/src/esp_image_format.o
Compiling .pio/build/esp32-s3-devkitc-1/bootloader_support/src/idf/bootloader_sha.o
Compiling .pio/build/esp32-s3-devkitc-1/cmock/CMock/src/cmock.o
Compiling .pio/build/esp32-s3-devkitc-1/console/commands.o
Compiling .pio/build/esp32-s3-devkitc-1/console/esp_console_repl.o
Compiling .pio/build/esp32-s3-devkitc-1/console/split_argv.o
*** [.pio/build/esp32-s3-devkitc-1/src/main.o] Error 1
Compiling .pio/build/esp32-s3-devkitc-1/console/linenoise/linenoise.o
===================================================================================== [FAILED] Took 3.71 seconds =====================================================================================
```

I even tried to remove the elapsedMillis library and make changes in the code, but then again, a new WiFi error appeared.
`src/main.cpp:6:10: fatal error: WiFi.h: No such file or directory.
``

By the way, I had to change the framework from esp-idf to espidf in the platformio.ini file; otherwise, it was showing an error.
`Error: This board doesn't support esp-idf framework!`
If i change it to arduino it compiles without any fuss but writing bin at 0x0 address also throws an error

`Using 'COM58' as serial port.
Showing logs:
[02:47:49]ESP-ROM:esp32s3-20210327
[02:47:49]Build:Mar 27 2021
[02:47:49]rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
[02:47:49]SPIWP:0xee
[02:47:49]mode:DIO, clock div:1
[02:47:49]load:0x3c080020,len:0x1b7f8
[02:47:49]load:0x3fc94810,len:0x47f8
[02:47:49]load:0x42000020,len:0x7f01c
[02:47:49]load:0x3fc99008,len:0xc2c
[02:47:49]load:0x40374000,len:0x10808
[02:47:50]SHA-256 comparison failed:
[02:47:50]Calculated: d6cff62ff0352a390f043fb666e480a44996fa16888003a1cc159eb89444ac71
[02:47:50]Expected: dacbd0f35f0b69fc735f406d6d587e181d822dc965297b30e2aa7cb01ec4f861
[02:47:50]Attempting to boot anyway...
[02:47:50]entry 0x40376900`

Also, I can see you have an ESPHome component. Can you please share the YAML so I can try that as well?

**Comment by KlaysDe** [comment]
Hi, 
thanks for the feedback.
I will look into that error when i got time, it worked fine on my side and since then I haven't touched the project.
Regarding the ESP home component, that is not functional. I tried to implement that, got stuck and left it as it was because this project here was working fine for me. Esp home would've just been a nice to have so i could run it as a "side-process" on an esp that does something else, but I couldn't find a way to get the esp freertos callbacks to work there. The code does not compile.

**Comment by mahipat99** [comment]
Thanks for the quick reply.
Oh, I didn't check properly; I thought you managed to get it working.

I am able to run the code now with the Arduino framework after flashing the bootloader and partition. It connects to WiFi/MQTT, but I don't see any input from the keyboard.
I tried a Logitech G213 keyboard and a generic wireless numpad (2.4GHz).

For debugging purposes, I attached a USB LED to check power on the OTG port, and there is no power. Do I need to make any changes?

**Comment by KlaysDe** [comment]
Are you using the esp32-s3 dev kit? there is a little jumper on the bottom that you need to solder to use it as an otg port.

![grafik](https://github.com/KlaysDe/esp32-s3_usb-keyboard-to-mqtt/assets/63735966/05c71aaa-c0d6-40f0-ace1-6fa51a02bd1b)

**Comment by mahipat99** [comment]
No, [devkitc-1-v1.0](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1-v1.0.html)
There is no jumper. When I press the on-board reset button, the light on the USB OTG port works for a second.

**Comment by KlaysDe** [comment]
https://dl.espressif.com/dl/SCH_ESP32-S3-DEVKITC-1_V1_20210312C.pdf

tbh, i don't know how a device on this board's usb should be powered, maybe I am overlooking something.

from what i see in the shematics, the usb otg port connects to a diode and a net label called vbusb which it not referenced at any other point in the document, and the diode prevents the voltage from the other USB port to power this one... 

![grafik](https://github.com/KlaysDe/esp32-s3_usb-keyboard-to-mqtt/assets/63735966/bc57cb9a-f80e-45bb-aea6-2ede4a18da05)

**Comment by mahipat99** [comment]
> from what i see in the shematics, the usb otg port connects to a diode and a net label called vbusb which it not referenced at any other point in the document, and the diode prevents the voltage from the other USB port to power this one...

Thanks for the heads-up. Looks like bridging the D7 or connecting VCC_5V to the anode is the solution.
